import { Component, EventEmitter, Output } from '@angular/core';
import { MovieVar } from '../models/movieVar';
import { MovieService } from '../services/movie.service';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-add-movie-component',
    standalone: true,
    imports: [FormsModule, CommonModule],
    templateUrl: './add-movie-component.html',
    styleUrl: './add-movie-component.scss'
})
export class AddMovieComponent {
    title: string = '';
  year: string = '';
  imageUrl: string = '';
  
  constructor(private movieService: MovieService) {}
  
  add() {
    const newmovie: MovieVar = {
      id: 0, // ID will be auto-generated by the service
      title: this.title,
      year: this.year,
      imageUrl: this.imageUrl
    };
    
    // Add movie using the service
    this.movieService.addMovie(newmovie);
    
    // Clear the form after adding
    this.title = '';
    this.year = '';
    this.imageUrl = '';
    
    console.log('Movie added successfully:', newmovie);
  }
}